stages:
  - build_and_push
  - deploy_staging

variables:
  DOCKER_IMAGE_NAME: $DOCKER_HUB_USER/user-service:$CI_COMMIT_SHORT_SHA

  SERVICE_NAME_STAGING: "user-service-staging"
  TARGET_PORT: "8080"

# --- STAGE 1: DOCKERIZE & PUSH TO DOCKER HUB ---
dockerize:
  stage: build_and_push
  script:
    - echo "Building Docker image..."
    # Log in Docker Hub
    - docker login -u $env:DOCKER_HUB_USER -p $env:DOCKER_HUB_PASS
    - docker build -t $env:DOCKER_IMAGE_NAME .
    - echo "Pushing Image to Docker Hub..."
    - docker push $env:DOCKER_IMAGE_NAME
  only:
    - staging

# --- STAGE 2: DEPLOY TO AZURE CONTAINER APPS ---
deploy_to_azure:
  stage: deploy_staging
  script:
    - echo "Connecting to Azure..."

    - $azureCreds = $env:AZURE_CREDENTIALS | ConvertFrom-Json

    - az login `
      --service-principal `
      -u $azureCreds.clientId `
      -p $azureCreds.clientSecret `
      --tenant $azureCreds.tenantId

    - echo "Setting Docker Hub registry..."

    - az containerapp registry set `
      --name $env:SERVICE_NAME_STAGING `
      --resource-group $env:AZURE_RESOURCE_GROUP `
      --server index.docker.io `
      --username $env:DOCKER_HUB_USER `
      --password $env:DOCKER_HUB_PASS

    - echo "Deploying new image..."

    - az containerapp update `
      --name $env:SERVICE_NAME_STAGING `
      --resource-group $env:AZURE_RESOURCE_GROUP `
      --image $env:DOCKER_IMAGE_NAME `
      --registry-server index.docker.io `
      --registry-username DOCKER_HUB_USER `
      --registry-password $env:DOCKER_HUB_PASS `
      --set-env-vars `
      "ConnectionStrings__DefaultConnection=$env:DB_CONNECTION_STRING"

  only:
    - staging
