<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Features\Auth\LoginOAuth2\**" />
    <EmbeddedResource Remove="Features\Auth\LoginOAuth2\**" />
    <None Remove="Features\Auth\LoginOAuth2\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit" Version="8.5.10" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.10" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Nexus.Shared.Contracts" Version="1.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Admin\Sellers\GetSellerApplicationById\" />
    <Folder Include="Features\Admin\Sellers\GetSellerApplications\" />
    <Folder Include="Features\Admin\Sellers\RejectSeller\" />
    <Folder Include="Features\Auth\VerifyEmail\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerceAuction.UserService.Domain\ECommerceAuction.UserService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>


