<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Reputation\Events\" />
    <Folder Include="Reputation\Ratings\" />
    <Folder Include="Reputation\Restrictions\" />
  </ItemGroup>
</Project>

