<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
  </ItemGroup>
 
  <ItemGroup>
    <Protobuf Include="Protos\internal_health.proto" GrpcServices="Server" />
  </ItemGroup>
</Project>